name: Set var from json
on: [push]

jobs:
  assign-from-json:
    runs-on: ubuntu-latest
    name: A test job to read a value from json as a variable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read a json file 
        uses: ./ 
        id: read
        with:
          input-file: 'package.json'
          input-property: 'author.name' # Exp: 'fiddlermikey'
